name: DevSecOps Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  semgrep:
    name: Static Code Analysis (Semgrep)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Semgrep
        run: pip install semgrep

      - name: Run Semgrep (free, local scan)
        run: |
          semgrep --config=auto --sarif --output=semgrep.sarif || true

      - name: Fail if high severity Semgrep findings
        run: |
          if grep -q '"severity": "ERROR"' semgrep-results.json; then
            echo "❌ Semgrep found high severity issues"
            cat semgrep-results.json
            exit 1
          else
            echo "✅ No high severity Semgrep findings"
          fi

  snyk:
    name: Dependency Vulnerability Scan (Snyk)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Run Snyk Test
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  secrets:
    name: Secrets Detection (TruffleHog)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Scan for secrets with TruffleHog
        uses: trufflesecurity/trufflehog@main
