name: DevSecOps Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  actions: read
  contents: read
  security-events: write  # ✅ Enables SARIF upload


jobs:
  semgrep:
    name: Static Code Analysis (Semgrep)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Semgrep
        run: pip install semgrep

      - name: Run Semgrep (free, local scan)
        run: |
          semgrep --config=auto --json --output=semgrep.json || true

      #- name: Upload Semgrep findings as artifact
        #uses: actions/upload-artifact@v4
        #with:
         # name: semgrep-findings
         # path: semgrep-results.json

      #- name: Upload SARIF to GitHub Code Scanning
        #uses: github/codeql-action/upload-sarif@v3
        #with:
          #sarif_file: semgrep.sarif

      #- name: Fail if high severity Semgrep findings
       # run: |
        #  if grep -q '"severity": "ERROR"' semgrep-results.json; then
         #   echo "❌ Semgrep found high severity issues"
          #  cat semgrep-results.json
           # exit 1
          #else
           # echo "✅ No high severity Semgrep findings"
          #fi

  snyk:
    name: Dependency Vulnerability Scan (Snyk)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: snyk test --json > snyk.json
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  secrets:
      name: Secret Scanning with TruffleHog
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4

        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.11'

        - name: Install TruffleHog
          run: pip install --user trufflehog

        - name: Add user bin to PATH
          run: echo "$HOME/.local/bin" >> $GITHUB_PATH

        - name: Run TruffleHog and output JSON
          run: trufflehog --json . > trufflehog.json || true
